import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    backgroundColor: 'black',
    padding: 10,
    flex: 1,
  },
  icon: {
    width: 40,
    height: 40,
  },
  text: {
    width: '100%',
    height: 30,
    borderRadius: 15,
    borderColor: 'black',
    borderWidth: 1,
    marginTop: 19,
  },
  view1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  view2: {
    width: 40,
    height: 40,
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 10,
  },
  article: {
    color: 'white',
    marginTop: 5,
    fontSize: 12,
  },
  playIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  slider: {
    borderWidth: 1,
    borderColor: 'orange',
    marginHorizontal: 120,
    marginTop: 5,
  },
  all: {
    color: 'white',
    alignSelf: 'center',
    fontSize: 20,
  },
  iconMenu: {
    width: 30,
    height: 30,
    margin: 10,
    tintColor: 'white',
    alignContent: 'center',
  },
  iconSearch: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  iconSearch1: {
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 7,
  },
  input: {
    color: 'grey',
    alignSelf: 'center',
    marginRight: 30,
    fontSize: 16,
  },
  list: {
    flex: 1,
    flexDirection: 'column',
    tintColor: 'white',
    padding: 10,
    alignContent: 'center',
    justifyContent: 'center',
  },
  list1: {
    flex: 1,
    flexDirection: 'column',
    tintColor: 'white',
    borderRadius: 10,
    margin: 8,
    alignContent: 'center',
    justifyContent: 'center',
  },

  viewContainer: {
    width: 150,
    height: 150,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    backgroundColor: '#0C1C5B',
    width: '100%',
    paddingTop: 30,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    paddingHorizontal: 10,
  },
  iconView: {
    width: 60,
    height: 66,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -40,
  },
  imageContainer: {
    width: '99%',
    padding: 10,
    borderRadius: 10,
    marginTop: 10,
  },
  image: {
    backgroundColor: '#0C1C5B',
    width: '100%',
    height: 150,
    borderWidth: 1,

    justifyContent: 'center',
    alignItems: 'center',
  },

  listView: {
    padding: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: 14,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  menu: {
    width: 25,
    height: 25,
    tintColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
  },
});
