import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  lea: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    //paddingTop: 100,
    //marginTop: 180,
  },
  image: {
    backgroundColor: '#0C1C5B',
    width: '100%',
    height: 200,
    borderWidth: 1,
    marginTop: -0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  menu: {
    width: 25,
    height: 25,
    tintColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    alignContent: 'center',
  },
  search: {
    marginTop: 20,
    color: 'white',
    fontSize: 28,
    fontWeight: 'bold',
  },
  view: {
    marginTop: 200,
    height: 280,
    width: 280,
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  ab: {height: '102%', width: '102%', flex: 1 / 3},
  header: {
    backgroundColor: 'transparent',
    width: '100%',
    paddingTop: 30,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  menu: {
    width: 40,
    height: 30,
    alignContent: 'center',
    margin: 8,
  },
  arrows: {
    tintColor: 'white',
  },
});
